name: Run Script and Create Pull Request

on:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          # Add any other setup steps you need here

      - name: Run Python Script
        run: cd vocabulary_gen && python main.py && ls

  # create-pr:
  #   needs: run-script
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v2

  #     - name: Set up Git
  #       run: |
  #         git config --global user.email "actions@github.com"
  #         git config --global user.name "GitHub Actions"

  #     - name: Commit and Push Generated Files
  #       run: |
  #         git add generated_files/
  #         git commit -m "Update generated files"
  #         git push

  #     - name: Create Pull Request
  #       uses: actions/github-script@v5
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
  #         script: |
  #           const fs = require('fs');
  #           const path = 'generated_files/';
  #           const files = fs.readdirSync(path);
            
  #           if (files.length === 0) {
  #             console.log('No generated files to commit.');
  #           } else {
  #             const octokit = new (require('@octokit/rest'))();
  #             octokit.authenticate({
  #               type: 'token',
  #               token: process.env.GITHUB_TOKEN,
  #             });
              
  #             const pr = await octokit.pulls.create({
  #               owner: context.repo.owner,
  #               repo: context.repo.repo,
  #               title: 'Update generated files',
  #               body: 'This pull request updates the generated files.',
  #               base: 'main',
  #               head: 'generated-files-branch',  // Create a branch with your generated files
  #             });
              
  #             console.log(`Pull request created: ${pr.data.html_url}`);
  #           }
